### ISSUE TITLE
Memory leak when writing plink files via the Python interface

### ISSUE THREAD

**Issue by bvilhjal** [fadern/libplinkio#3]
Hi,

Thanks for writing this neat little package!

I noticed that if I repeatedly create, write and close lots of identical plink (bed) files consecutively, via the python interface, the memory increases usage blows up, suggesting that the actual genotypes are copied and kept in memory.

**Comment by hakon-jon** [comment]
Hey,

Maybe the discussion in this issue will help you
https://github.com/fadern/libplinkio/issues/2
 @fadern provided a patch and a workaround (explicitly calling gc.collect()) to 
deal with a similar problem. 

There is also handy code snippet in the discussion, which can 
help to create a minimal example for debugging.

Best,
Hákon

**Comment by fadern** [comment]
Hi Bjarni

Are you creating or opening the files? Which version are you using?

It is quite likely that there is a leak in create, I did not go through that when I worked with Hákons issue. I will look at it tomorrow, thanks for finding it.

Best,
Mattias

**Comment by bvilhjal** [comment]
Hi Mattias and Hakon, and thanks for the replies!  

I'm using plinkio on linux, and with python 2.6 (as 2.7 isn't installed on the system).  And I'm pretty sure that this is a real bug, and not just me doing something stupid.

Given some genotypes, positions, SNP IDs, etc., then the following code causes the memory to increase linearly with the number of iteration.  Calling the garbage collector explicitly and deleting things on the python side doesn't seem to help.  

for j in range(100):
    print 'Writing PLINK bed file: %s'%plink_prefix
    #Create samples
    samples = []
    for i in range(num_indivs):
        iid = 'i%d'%i
        fid = iid
        phenotype = 1
        sex = 0 # 
        affection = 2 # Corresponds to a quantitative phenotype
        indiv = plinkfile.Sample(fid, iid, iid, iid, sex, affection, phenotype)
        samples.append(indiv)
    
    #Creating plinkfiles
    wpf = plinkfile.WritablePlinkFile(plink_prefix, samples)
    
    #Now iterating over SNPs.
    for name, row, bp_position, chromosome, nt in it.izip(sids, genotypes, positions, chromosomes, nts):
        position = 0 #map position
        allele1 = nt[0]
        allele2 = nt[1]
        locus = plinkfile.Locus(chromosome, name, position, bp_position, allele1, allele2)
        wpf.write_row(locus, row) 
    wpf.close()

Best,
Bjarni

ps. there's a small bug in the pio_create function in plinkio.c, as it can return an arbitrary error number when there's no error.

**Comment by fadern** [comment]
Hi Bjarni

Thanks for the information and the example code.

Ok, definitely something going on with the memory. I took a modified version of your example and created 10 plink files. As we can see the memory is not returned properly. Probably missing refcounts in the create method, I'm looking into it now.

    Line #    Mem usage    Increment   Line Contents
    ================================================
         6      8.3 MiB      0.0 MiB   @profile
         7                             def main( ):
         8      8.4 MiB      0.0 MiB       plink_prefix = os.path.join( os.path.dirname( os.path.realpath( __file__ ) ), "mem.plink" )
         9      8.4 MiB      0.0 MiB       num_samples = 2000
        10      8.4 MiB      0.0 MiB       num_snps = 20000
        11      8.4 MiB      0.0 MiB       genotypes = [0] * num_samples
        12
        13      8.4 MiB      0.0 MiB       samples = []
        14     10.7 MiB      2.3 MiB       for i in range( num_samples ):
        15     10.7 MiB      0.0 MiB           iid = "i%d" % i
        16     10.7 MiB      0.0 MiB           fid = iid
        17     10.7 MiB      0.0 MiB           phenotype = 1
        18     10.7 MiB      0.0 MiB           sex = 0
        19     10.7 MiB      0.0 MiB           affection = 2
        20     10.7 MiB      0.0 MiB           indiv = plinkfile.Sample( fid, iid, "0", "0", sex, affection, phenotype )
        21     10.7 MiB      0.0 MiB           samples.append( indiv )
        22
        23     21.3 MiB     10.6 MiB       for j in range( 10 ):
        24                                     # Creating plinkfiles
        25     20.8 MiB     -0.5 MiB           wpf = plinkfile.WritablePlinkFile( plink_prefix, samples )
        26
        27                                     #Now iterating over SNPs.
        28     21.1 MiB      0.3 MiB           for i in range( num_snps ):
        29     21.1 MiB      0.0 MiB               locus = plinkfile.Locus( 1, "snp", 0, i, "A", "T" )
        30     21.1 MiB      0.0 MiB               wpf.write_row( locus, genotypes )
        31     21.3 MiB      0.2 MiB           wpf.close( )
        32
        33     21.3 MiB      0.0 MiB       gc.collect( )

**Comment by fadern** [comment]
I think I have managed to find the leaks now. I ran the example program above, and printed the objects that were still alive after GC and found initially:

    instance                   10011
    function                   1846
    wrapper_descriptor         1046
    builtin_function_or_method 748
    dict                       566
    method_descriptor          431
    tuple                      388
    weakref                    363
    list                       235
    member_descriptor          230

As we can see there is 10k instance objects, that should have been cleared. I added reference decrements for every call that incremented the reference counts in Python interface. After these changes I find:

    function                   1846
    wrapper_descriptor         1046
    builtin_function_or_method 748
    dict                       566
    method_descriptor          431
    tuple                      388
    weakref                    363
    list                       235
    member_descriptor          230
    property                   183

At least there are no longer objects leaked that is a function of the number of samples or variants. If you have time, please try this out and see if it solves your problems.

Also, note, there is a known garbage collection bug in Python 2.6 that causes the runtime to blow up when you create many objects, which could be the case if you create many Locus objects. Here is a link to the issue, it has been fixed in 2.7 and 3.0:
http://bugs.python.org/issue4074

Best,
Mattias

**Comment by bvilhjal** [comment]
Thanks Mattias!

I think you've fixed it.
